### ISSUE TITLE
labelSources enum is missing in BuildInterfaces

### ISSUE THREAD

**Issue by yrtimiD** [Microsoft/azure-devops-node-api#115]
labelSources property values enum is missing in BuildInterfaces.
It is part of BuildDefinition and can be found under: 
```
BuildDefinition {
  repository: BuildRepository {
     properties: {
        [key: string]: string;
    };
  }
}
```

Also, can't find it on [Contracts Index](https://www.visualstudio.com/en-us/docs/integrate/api/contracts-page)

**Comment by stephenmichaelf** [comment]
@yrtimiD Are you still having this issue? It looks like this field wasn't generated and may not exist on the REST endpoint? These are automatically generated.

**Comment by yrtimiD** [comment]
@stephenmichaelf, I'd really like to have it properly typed. Otherwise, setting label source programmatically becomes really unclear since you can't know which values are acceptable and need to do reverse engineering to get them.
For example:
OnSuccessfulBuild = 6,
OnEveryBuild = 46
etc.

**Comment by damccorm** [comment]
I don't think this is something we can support in this library since it doesn't exist on the endpoint. In general, it seems like they don't provide enums for things like this properties field which have a lot of different possible keys. If this is something you need, I'd recommend logging this with the developer community for a service change. The node api is generated from the service and this is a feature request of the service.

https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by damccorm** [comment]
I'm going to close, feel free to reopen if appropriate.
