### ISSUE TITLE
Provide public Gallery API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/azure-devops-node-api#126]
It would be great if this library would provide an API to access the Marketplace Gallery in a public way.

[vsce](https://github.com/Microsoft/vscode-vsce), the VS Code's extension packaging tool, now implements [a version of this](https://github.com/Microsoft/vscode-vsce/blob/master/src/publicgalleryapi.ts).

**Comment by stephenmichaelf** [comment]
@joaomoreno Is [this](https://github.com/Microsoft/vsts-node-api/blob/master/api/GalleryApi.ts) what you're looking for? It has the ability to work with extensions like the code you referenced.

**Comment by joaomoreno** [comment]
No, I mean the public API. That's the private one. VSCE uses that one extensively already.

**Comment by stephenmichaelf** [comment]
@joaomoreno I saw the issue that referenced this above, 238, was closed on your end. This may still be an issue we have. We have had several other customers update to the latest version of this library and none of them are having issues. 

The HttpClient used in this library comes from our typed-rest-client, it doesn't live in this library. Could you describe how you are using it a bit more so I can try to find out if/where there is a problem? Thanks!

**Comment by joaomoreno** [comment]
The current version of `vsts-node-api` doesn't expose public extension querying. All REST methods require authentication. Did I get this wrong?

So, we created our own methods for querying publicly: https://github.com/Microsoft/vscode-vsce/blob/master/src/publicgalleryapi.ts#L1 This is a hack, which stopped working in the latest `vsts-node-api`.

This issue refers to exposing that public API, so we don't do the hack.

**Comment by raix** [comment]
It's correct that the `getGalleryAPI` requires auth - thats why we use the `HttpClient` *(moved to a separate package "typed-rest-client" in final release of the node-api == breaking the "hack")*

We could update vsce to use the `typed-rest-client` but it might break again in the future?

I'm not sure how the public api access is implemented in vs code "extension search" etc. *(same endpoint though)*

**Comment by stephenmichaelf** [comment]
Thanks for the clarification.

@joaomoreno Yes authentication is required.

My recommendation would be to change to the typed-rest-client. If by break you mean get moved to a new repo, that is unlikely as the sole purpose of the library is now to be a rest/http client. Single responsibility.

@bryanmacfarlane Does that make sense to you too?

**Comment by raix** [comment]
@stephenmichaelf All dependencies are `vsts-node-api` internals https://github.com/Microsoft/vscode-vsce/blob/master/src/publicgalleryapi.ts#L1-L5 so really tight coupled (not to mention api versions/endpoint details).

I could help make a pr if you want - the footprint would be around 50 lines

(reference to [similar code in vs code](https://github.com/Microsoft/vscode/blob/8c5452be2d159ae415e2effe95b7f1a3a383f7f2/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L427))

**Comment by damccorm** [comment]
Looks like this should be fixed by #233

**Comment by raix** [comment]
@damccorm we need to use the public Gallery api (public == no need to set auth handler)

**Comment by damccorm** [comment]
Ah, gotcha, thanks for clarifying.

Upon investigation, it looks like the thing that is holding the library back from this currently is the call in every method to [vsoClient.getVersioningData](https://github.com/Microsoft/azure-devops-node-api/blob/6525ead92dcbbd585a7d73e6360ea28afe9a3146/api/VsoClient.ts#L117), which eventually triggers a [call to the rest client](https://github.com/Microsoft/azure-devops-node-api/blob/6525ead92dcbbd585a7d73e6360ea28afe9a3146/api/VsoClient.ts#L164) which returns a promise of a VssApiResourceLocationLookup object. This object contains information used to construct a [ApiResourceLocation](https://github.com/Microsoft/azure-devops-node-api/blob/6525ead92dcbbd585a7d73e6360ea28afe9a3146/api/interfaces/common/VsoBaseInterfaces.ts#L15) object which has all the information we need to construct the appropriate request, including the routeTemplate and versioning info. Without this information, we can't construct the request. I see several possible options for addressing this:

1. Find a non-authenticated alternative to the current rest call which returns a VssApiResourceLocationLookup object. This would be ideal, but I don't think that endpoint exists.

2. Have users manually pass in the entire request URL. This would work, but also isn't very helpful - I think at this point we might as well just instruct people to use the typed-rest-client and create their own requests. This solution isn't really in line with the rest of what this library does and is probably out of the scope of what we are trying to do.

3. Write these functions ourselves and manually code in the key pieces we need (e.g. route template, versioning info). It seems like that is basically what [vsce](https://github.com/Microsoft/vscode-vsce/blob/master/src/publicgalleryapi.ts) is doing, combined with a little bit of option 2. While this is helpful in certain cases, this goes against one of the core ideas of this library, which is decoupling the updating of this client from changes in the REST API. When the API is changed, we're able to just regenerate, push here, and all of that functionality is exposed with minimized risk of bugs. This option would remove that decoupling and require manual updates as the APIs change, creating a higher chance of bugs and unexposed functionality.

4. Do nothing/recommend that users create and send their own requests using typed-rest-client. I lean towards this option.

I'm open to other options other than what I've listed here, but I think as of now I'd lean towards sticking with option 4 and avoiding non-generated APIs here.

**Comment by raix** [comment]
Regarding 3. `vsce` is doing more or less what `vs code` does in [extensionGalleryService.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L487)

Agree with 1. if that's the missing link for this module to be able to add support for requests against the public api.

I guess my point it that I would argue that it would be the responsibility of this library to provide at least parts of the public api - if not possible we should consider creating a new module `azure-devops-public-node-api`

**Comment by damccorm** [comment]
Several thoughts:
- I think the more that I think about it, the less attractive option 3 is. Right now, we use info from the API to autonegotiate versioning info. Without that, I think this would break for some users who are using TFS.
- I've looked around and haven't been able to find a great alternative for option 1. I may have a way to get the route template, but that alone doesn't solve any of our problems.
- I don't know if its unreasonable to expect users of this library to have some form of auth. I think that to use any of the functionality exposed by the other APIs you need auth, so it may be best to just position this library as always requiring auth.

**Comment by damccorm** [comment]
@stephenmichaelf, any thoughts on this? I'm somewhat torn on the best way to proceed (though I'm leaning towards a no-op), you might have better perspective/context

**Comment by stephenmichaelf** [comment]
I reached out to @tedchamb to see how the C# client handles it. We normally try to keep parity with their feature set.

**Comment by raix** [comment]
We currently have no option to authenticate in vsce it might be the same in vs code? when searching for extensions in the gallary. Also having to authenticate in order to use a public api sounds contradicting.

**Comment by damccorm** [comment]
@raix, agreed that you don't need auth for those libraries - they're also not supporting things like autonegotiating versioning info (which is part of why we currently need auth) and they aren't autogenerated like this library (which provides other advantages). It might be that we can't have auth without giving up one/both of those things, though I'm interested in how the C# client handles it.

Regarding your last concern, I don't think its a contradiction - this is a public API mostly for accessing/manipulating Azure Devops accounts which are private - the exception here is the Gallery API as far as I can tell. Since we're accessing private accounts, it makes sense to have auth.

**Comment by damccorm** [comment]
Just did a little digging, looks like the C# client doesn't provide a public option - they use the same endpoint to create their requests. Because of that and the other aforementioned reasons, I think this should be a no-op. My recommendation for now would be to just create/send the requests using the typed-rest-client. Basically its going to be the same logic as here, you just need to hardcode the location endpoint data.

**Comment by damccorm** [comment]
I'm going to close, feel free to reopen if you have more thoughts and/or questions though.

**Comment by joaomoreno** [comment]
That's too bad. Can you quickly review https://github.com/Microsoft/vscode-vsce/blob/master/src/publicgalleryapi.ts?

**Comment by damccorm** [comment]
@joaomoreno this generally looks fine to me, a couple thoughts though.

1) We use queryParams to encode variables into the url instead of passing them in the request as data. Not sure if the API is ok accepting them both ways or not, but the recommended way for [all of these REST API's](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1) is through the url. So with your parameters our requests end up looking like: {base_url}/_apis/public/gallery/extensionQuery?pagenumber={pagenumber}&pageSize={pageSize}&flags.a={flags.a}&flags.b={flags.b}&etc...

2) Similarly, we encode the extensionId as a [route value](https://github.com/Microsoft/azure-devops-node-api/blob/8b877def56f58a581edb29debd8c7c6f4b37d481/api/GalleryApi.ts#L1635), which means it gets placed in the url like: {base_url}/_apis/public/gallery/extensionQuery/**{extensionId}**?{queryValues}. Again, not really sure whether the API can accept it the way you're sending it/will support that going forward, but that is at least how we do it and our code is generated directly from the REST endpoint.

**Comment by joaomoreno** [comment]
@damccorm Thanks! Created https://github.com/Microsoft/vscode-vsce/issues/297
