### ISSUE TITLE
gitApi()getItem on tgz files

### ISSUE THREAD

**Issue by jycouet** [Microsoft/azure-devops-node-api#128]
Hi, 
I'm able to get all files of my repo with this and their **fileContent**
```
function getContent() {
  const item = await connect.gitApi().getItemText( ... )
  const fileContent = await streamToString(item);
}

async function streamToString(stream) {
  const chunks = [];
  const p = await new Promise(resolve => {
    stream.on('data', chunk => {
      chunks.push(chunk.toString());
    });
    stream.on('end', () => {
      resolve(chunks.join(''));
    });
  });
  return p;
}
```

But I have a problem with tgz files. 
Do you know how should I do this?

Thank you

**Comment by stephenmichaelf** [comment]
I will take a look, thanks for letting us know!

**Comment by damccorm** [comment]
From the documentation: "The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content, which is always returned as a download."

https://github.com/Microsoft/azure-devops-node-api/blob/91cc61009898b0f8656cba70e54fff63257e734f/api/GitApi.ts#L1723

Looks like the issue here is that tgz files can't be sent as a stream because its being returned as a downloaded file and must be retrieved as such. More info on how it is being returned here: https://docs.microsoft.com/en-us/rest/api/vsts/git/items/get?view=vsts-rest-4.1#download

**Comment by stephenmichaelf** [comment]
Thanks for taking a look, closing this as it doesn't seem to be a bug with the node api. Expected functionality.
