### ISSUE TITLE
ExtensionManagementApi:  add field validation

### ISSUE THREAD

**Issue by pabrams** [Microsoft/azure-devops-node-api#177]
I just spent most of the afternoon trying to figure out why the API thinks my documentCollection doesn't exist even though I can see it in the database, and it turns out it's because the collection name is too long for the stored proc ([Extension].[prc_GetDocuments]):
    @collectionName         NVARCHAR(50),

but in other procs, and in the database, the size is bigger, e.g. from [Extension].[prc_iGetCollection]):
    @collectionName         VARCHAR(100),

Also, the table itself has nvarchar(100).

Notwithstanding the discrepancy, could the API validate this for us and throw an error if the values are too long, instead of telling me incorrectly that the collection does not exist?

**Comment by damccorm** [comment]
I think this is basically just an extension of #178 (its the same basic problem, just a different proposed solution), so they should probably be tracked together. This is especially true since we don't control the solution, that's up to the team that owns the API, so our response is going to be the same for both. I'm going to close this one and we'll track it in #178.
