### ISSUE TITLE
Samples in plain JavaScript

### ISSUE THREAD

**Issue by justin0022** [Microsoft/azure-devops-node-api#255]
Is there a chance we can get plain JavaScript samples, instead of TypeScript? Even a transpilation to regular JS would be helpful for people not used to reading/writing TS.

**Comment by damccorm** [comment]
I think since this is a TypeScript library we're going to keep the samples as TypeScript. With that being said, if you run the following in the base directory, it will transpile all of the samples to JS - they will show up in the samples folder next to the TS versions:
```
npm install
npm test
```

In addition, if you copy and paste any TS file in the left pane [here](https://www.typescriptlang.org/play/index.html), transpiled JS will show up in the right pane. Just be careful because I believe that transpiles to the es5 standard while this library transpiles to es6.

Lastly, if you want to learn TypeScript, check out [this resource](https://basarat.gitbooks.io/typescript/content/)!
