### ISSUE TITLE
Unable to display projects using a pick list

### ISSUE THREAD

**Issue by thusithagh** [Microsoft/azure-devops-node-api#257]
### Environment
Node version: v8.11.1
Npm version: 5.6.0
OS and version: Windows 10
azure-devops-node-api version: 6.6.3

### Issue Description
Unable to display projects list using a pick list

### Expected behaviour
The pick list should be populated with project names

### Actual behaviour
The pick list is empty

### Steps to reproduce
Following is my pick list definition:
{
      "name": "project",
      "type": "pickList",
      "label": "Project",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "Select the root area.",
      "properties": {
        "DisableManageLink": "True"
      }
    }

Following is the source definition:

{
      "target": "project",
      "endpoint": "http://localhost:8080/tfs/DefaultCollection/_apis/projects?api-version=1.0",
      "selector": "jsonpath:$.name",
      "keySelector": "jsonpath:$.name",
      "authKey": "tfs:teamfoundation"
    }

My local environment has TFS 2015, and the URL works fine in the browser. However, the pick list is not getting filled up in the extension.

Any idea what has gone wrong here?

**Comment by damccorm** [comment]
Hi, could you provide a little more info on how you're using the node api? Are you calling [getProjects](https://github.com/Microsoft/azure-devops-node-api/blob/e852eb96355ff697564e16cb02578450c3076445/api/CoreApi.ts#L36)? Also, are you able to verify that the issue is with getting the project info and not populating the pick list?

If the issue is indeed with getting the project info, my instinct is that its an authentication issue - that would explain why something is working in the browser (where you may have some sort of preauth already configured) but not in the extension. I'd need more info to accurately diagnose the issue though.

**Comment by bryanmacfarlane** [comment]
This doesn't appear to be an issue with node api.  It looks like a UI extension question/issue, right?

**Comment by thusithagh** [comment]
Yeah. This is related to UI. Can you please point me the correct place to ask, if this is not the one?

Thank you.

Best Regards,
Thusitha

**Comment by damccorm** [comment]
It definitely seems like its not an issue with the node-api if you're not making any node-api calls. It probably would be better suited for https://github.com/Microsoft/azure-pipelines-tasks. With that being said, I'd also recommend taking a look at some of the tasks in that library that use picklists before proceeding. Most of them have predefined options, but some (e.g. [PackerBuildV0](https://github.com/Microsoft/azure-pipelines-tasks/blob/ed4b9e2237f45bfa7ae417ca598907efce92e7dd/Tasks/PackerBuildV0/task.json#L239) already do what you're trying to). I think there might also already be a couple issues in that repo that talk about similar things.
