### ISSUE TITLE
distributedtask postEvent method is missing

### ISSUE THREAD

**Issue by ribrdb** [Microsoft/azure-devops-node-api#279]
The post event method required for marking an async agentless http task as done is missing.
https://blogs.msdn.microsoft.com/aseemb/2017/12/18/async-http-agentless-task/
{"id":"557624af-b29e-4c20-8ab0-0399d2204f3f","area":"distributedtask","resourceName":"events","routeTemplate":"{scopeIdentifier}/_apis/{area}/hubs/{hubName}/plans/{planId}/{resource}","resourceVersion":1,"minVersion":"2.0","maxVersion":"5.0","releasedVersion":"5.0"}

**Comment by damccorm** [comment]
I'm not quite sure what you're referring to, the link doesn't reference a postEvent method. Is this something that exists on the C# client that you're expecting to see on the node client? Or is it just a method you'd like to see an implementation for?

**Comment by damccorm** [comment]
Thanks for the clarification - after some discussion, I don't think we're going to add this. This is written by hand in the C# client for some legacy/backcompat reasons which would also apply here. To avoid things getting out of sync/other concerns we don't want to add it here.

My recommendation would be to manually construct the request using the [typed-rest-client](https://github.com/Microsoft/typed-rest-client), you can construct the url/options and make the call the same way we do in the other APIs (for example, [in the Git API](https://github.com/Microsoft/azure-devops-node-api/blob/be95c4d99fff7a50ef6590a2dbb246f6ab5063be/api/GitApi.ts#L227)).

**Comment by damccorm** [comment]
I'm going to close for now, please reopen if you have more thoughts and/or questions about this.

**Comment by ribrdb** [comment]
I'm sorry, maybe this is more an issue for the azure pipelines people, but I think this is ridiculous.
The [Invoke REST API task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=vsts) has a completion event option to allow an async callback. But there's no official documentation anywhere on how to make the callback. The only thing I can find is that blog post, which is using an undocumented rest api via the c-sharp client. And you refuse to add the api to your official client for other languages. So why does this feature even exist then?
How would I make this call using the typed-rest-client? Do I have to look it up by using vsoClient.getVersioningData and the unique id? Or can I assume the url won't change? If the only way to use this is to look it up by the id shouldn't you at least document the id somewhere, or else stop pretending this is a feature people can use.

**Comment by damccorm** [comment]
As long as you continue to target the same version of the API, the url shouldn't change, sorry I should have been more clear about that.

To elaborate a little more on why we're not adding it in this library: For the most part we try to maintain parity across our libraries to avoid these sorts of problems. One exception to this is that we don't need to maintain complete parity for some agent specific functionality because [the agent](https://github.com/Microsoft/azure-pipelines-agent) is written in C#. This maybe shouldn't be roped into that category, but unfortunately implementation-wise I think it has been. There's a lot of context here (some of which I don't even know) that would make changing this more intensive than it would seem at first glance. One specific cause of this is that the C# client doesn't autogenerate this method (unlike the rest of this library which is basically all autogenerated), so maintaining consistency between versions and ensuring changes aren't breaking becomes challenging/risks leaving behind broken methods. One of the big central principles behind this library is that it shouldn't require maintainers to keep track of API changes, we can just regenerate from the endpoints.

Lastly, agreed that the documentation on this could definitely use some love. Would you mind creating an issue for this at the bottom of the page you linked? I'd do it, but I think it would be better coming from you, and you could probably get better info on your particular use case.
