### ISSUE TITLE
Add Operation API

### ISSUE THREAD

**Issue by uma1966** [Microsoft/azure-devops-node-api#281]
### Environment
Node version: v8.12.0
Npm version: 6.4.1
OS and version: Windows 10
azure-devops-node-api version: 7.0.0

### Issue Description
Please add Operations API.
When creating a project with the Core API (queueCreateProject) an OperationReference is returned. It would be nice to be able to query the operation status but the corresponding API is not implemented in this package.

### Expected behaviour
Be able to query the Operation API (https://docs.microsoft.com/de-de/rest/api/azure/devops/operations/operations/get) with this package.

### Actual behaviour
No API for Operations is available within this package.

### Steps to reproduce
1. Create project with Core / Projects API

### Logs
n/a

**Comment by damccorm** [comment]
In general, we just try to maintain parity with the .Net client, they control which APIs get generated. I don't believe this exists on the .Net client, so we won't add this here right now.

Could you follow up with the .Net client folks by creating an issue in [this repo](https://github.com/Microsoft/vsts-dotnet-samples/issues)? I would do it, but it would probably be better coming from you since you can better explain use case/etc...

I'll close here for now, but please reopen if appropriate.

**Comment by bengreenier** [comment]
Hi @damccorm - Seems like this is still missing, and I believe I am seeing it used in [the referenced repo](https://github.com/microsoft/azure-devops-dotnet-samples/blob/62bda633ca49b960bd0eeb1c7c0d36b53d046b58/ClientLibrary/Samples/ProjectsAndTeams/ProjectsSample.cs#L206) - Any chance we can get this added/supported here? I'm working on a tool to be used with some of our partners @ ms, and being able to check status of queued project creation operations is key.

Please let me know if i'm misunderstanding the usage in the other repo - maybe it's still not a public API there yet either.

**Comment by jamiemccrindle** [comment]
This would be useful for me too.
