### ISSUE TITLE
Code search client

### ISSUE THREAD

**Issue by wsmckenz** [Microsoft/azure-devops-node-api#282]
### Environment
Node version: 8.11.1
Npm version: 
OS and version: all
azure-devops-node-api version: 6.6.2

### Issue Description
There doesn't seem to be a client for the code search api. I know the API pretty well, and have used it in other environments/languages. My question is just this: is there any value in trying to use the basic WebApi class to call a generic url against the API and take advantage of common authentication, error handling, etc. without having a specific client, or should I just call the API directly using plain old nodejs functionality?

**Comment by damccorm** [comment]
I would say the biggest advantage of using the WebApi is that it has all of the stuff you mentioned built in abstracted away and you can be sure it works without having to reinvent the wheel and. With that being said, if you're just looking to do ad-hoc queries against an API you know well, you might just be better off using the [typed-rest-client](https://github.com/Microsoft/typed-rest-client) since its lighter weight and has most of the same stuff built in. Mostly what the WebApi eventually does is send/receive requests using the typed-rest-client's RestClient class anyways.

**Comment by damccorm** [comment]
I'm going to close, please reopen if you have additional thoughts/questions
