### ISSUE TITLE
samples/build.ts issues with coding practices in the sample

### ISSUE THREAD

**Issue by ashwinsaval** [Microsoft/azure-devops-node-api#286]
### Environment
Node version: 8.11.3
Npm version: 5.6.0
OS and version: Mac OS 10.14.3 (Mojave)
azure-devops-node-api version: Irrelevant

### Issue Description

I am looking at this sample https://github.com/Microsoft/azure-devops-node-api/blob/master/samples/build.ts and I cannot seem to understand why we are doing things this way. Is it intentional or for demonstration.

1. https://github.com/Microsoft/azure-devops-node-api/blob/master/samples/build.ts#L25
Why do we need a for loop to extract the last definition in a list of already extracted definitions?

2. https://github.com/Microsoft/azure-devops-node-api/blob/master/samples/build.ts#L80
Variable `newProcess` is created but never used. Are we supposed to be using it somewhere?

3. Related to Point 2: https://github.com/Microsoft/azure-devops-node-api/blob/master/samples/build.ts#L74
Looks like the `steps` variable created here is useless as well since `newProcess` is not used anywhere either.

4. https://github.com/Microsoft/azure-devops-node-api/blob/master/samples/build.ts#L112 for the life of me I cannot understand why the `JsonPatchProperties` is defined like this. Official documentation at https://docs.microsoft.com/en-us/rest/api/azure/devops/build/properties/update%20definition%20properties?view=azure-devops-rest-5.0#jsonpatchdocument is of no help either (no examples). Has an internal implementation detail leaked here somehow?

Can somebody help me understand what is happening?

**Comment by ashwinsaval** [comment]
cc: @bryanmacfarlane @stephenmichaelf @scottdallamura @kimsey0

**Comment by damccorm** [comment]
Sure. By nature some of the samples are a little arbitrary since they're just trying to demonstrate functionality not solve a real world problem, but I'll try to explain what we're doing:

1. We're not trying to extract just the last definition. What we are doing is taking a list of `DefinitionReference` objects and for each of them extracting the richer `BuildDefinition` object, and then ultimately the `repository` info from that. You might want to do something like this because its less expensive to acquire the smaller `DefinitionReference` object than the larger `BuildDefinition` object and you might not need the whole `BuildDefinition` for some of the builds you are looking at.

2. This is a mistake, looks like this got left in when we refactored. After this I'll add a PR to either get rid of it or use it.

3. Same as (2)

4. Not 100% sure where the confusion lies here - basically there are 6 different operations available (add/copy/move/remove/replace/test) and you need to provide the path and value for the operation. So in this case we are updating the definition by replacing the value at `/key1` with `/value1`. Not sure if I answered your question here, let me know if you have further follow ups.

**Comment by ashwinsaval** [comment]
@damccorm thanks for following up. My follow ups point by point below:
1. I understood that you want to expose the need for `vstsBuild.getDefinition` to get complete details for a build definition. I don't understand however, the need for a for loop, that extracts the complete definition for all definitions. We only need complete definition information for only the last definition, correct?

Can this not be written in the following manner:
```
const lastDefRef = defs[defs.length - 1];
const lastDef: bi.BuildDefinition = await vstsBuild.getDefinition(lastDefRef.id, project);
const lastDefRep: bi.BuildRepository = lastDef.repository;
```
I believe it demonstrates the need to use `getDefinition` amply while still using real world programming practices.

2. and 3.: Thanks for taking this up. Wasn't sure what was happening there

4. To elaborate what I meant to say, I cannot find any documentation anywhere for what the `JsonPatchProperties` should look like for the six operations mentioned. To make my confusion clear, I only need an answer to the following questions:
  a. What does the `JsonPatchProperties` look like for the 6 different operations mentioned
  b. If the answer to question a. is an official documentation I may have missed, which one is it? So far I could only find [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/properties/update%20definition%20properties?view=azure-devops-rest-5.0#jsonpatchdocument) which is not helpful at all. There are no examples for what the JSON body looks like for the different operations.

**Comment by damccorm** [comment]
1. That would be valid as well, we just happen to also be printing out some info about the other builds as well. Just doing slightly different things, again its kinda arbitrary since its samples 😄 

4. I'm still not quite sure what you're asking for. There's not a `JsonPatchProperties` object as far as I know, do you mean `JsonPatchDocument`? If so, I think the docs you pointed to basically lay it out - there are 4 fields, `from`, `op`, `path`, and `value`. `from` is only needed for some of the operations, but you should always specify the other 3. `op` is chosen from add/copy/move/remove/replace/test, `path` is the path you want to perform the operation on, and `value` is either a primitive or JToken that you are using as the value of the operation. So in the example we are replacing the value at path `/key1` with the value `/value1`.

**Comment by ashwinsaval** [comment]
@damccorm replies pointwise:
1. Fair enough, since its a sample it's alright
2. My bad. I meant `JsonPatchDocument`. You were right, that is what I was looking for and thanks for the explanation. However, I cannot see your explanation in the link I shared. Is there an alternate resource I could refer for this usage.

In summary, this issue is dragging along now. We can close the issue since the remaining issues are documentation related which don't require this issue to be open.

Thanks @damccorm. Appreciate the assistance 👍

**Comment by damccorm** [comment]
I don't think this is documented anywhere else. With that said, I think everything I said is in the docs you linked to - I honestly haven't used this API before personally so I was just drawing from the docs in my answer. If you disagree/think that they're not clear, I'd recommend adding an issue in [this repo](https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues), that's where we track our Rest Doc issues.
