### ISSUE TITLE
Generate governance API

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/azure-devops-node-api#363]
Not sure how/where the APIs are generated from, but the governance API is available [here](https://github.com/MicrosoftDocs/vsts-rest-api-specs/tree/master/specification/governance) in vsts-rest-api-specs.

Is it possible to generate the applicable API?

**Comment by JamieMagee** [comment]
@damccorm the Governance API wasn't generated in the most recent update. Is it possible to do a patch release to include it? Documentation [is public](https://docs.microsoft.com/en-us/rest/api/azure/devops/componentgovernance/?view=azure-devops-rest-6.0&branch=mseng%2Ffeatures%2FGovernance%2Fnew-api-docs).

**Comment by damccorm** [comment]
It looks like the Governance api is currently not generated for any of our libs (e.g. Python, Java, etc...). That can change, but would require the internal Governance team's signoff/ownership. Since its not specifically our generated library, the best path forward is probably to file a ticket in devcom so it gets routed to the right owners there - https://developercommunity.visualstudio.com/spaces/21/index.html
