### ISSUE TITLE
How should I use timeouts/retries to avoid ETIMEDOUT

### ISSUE THREAD

**Issue by rfennell** [microsoft/azure-devops-node-api#378]
### Problem
I have been seeing a problem with an Aure DevOps task when it is making a large number of API calls i.e. when generating release notes where there are hundreds of associated items to get details for. 

I am guessing it is a throttling issue.

I see the error, but not at a consistent point in the logic

```
Error: connect ETIMEDOUT 13.107.42.18:443
```

The strange thing is this only occurs for hosted agent, a private agent is fine. 

My assumption is that this is down to the increased latency from an agent hosted on my local network as opposed to one in an Azure data centre.

### Environment
Node version: 12.16.1
Npm version:  6.13
OS and version: Problem seen on MS Hosted Agent VS2017-win2016
azure-devops-node-api version:  10.1.0

### What I have tried
I have tried adding retry/timeout options when I initialise my WebApi, but it does not appears to have had any effect.

A code snippet of the initialiser for the WebApi is
```
import * as vstsInterfaces from "azure-devops-node-api/interfaces/common/VsoBaseInterfaces";
// load creds handler from helper function
let credentialHandler: vstsInterfaces.IRequestHandler = util.getCredentialHandler();
const options = {
                allowRetries: true,
                maxRetries: 20,
                socketTimeout: 30000,
} as vstsInterfaces.IRequestOptions;
let vsts = new webApi.WebApi(tpcUri, credentialHandler, options);
```
### Question
However, this does not seem to have helped.

1. Have I missed something else I need to do? 
1. Or must I wrapper each API call in my own retry code?

**Comment by rfennell** [comment]
Is there any news on this issue?

I have been trying to do more testing

- If I run an Azure DevOps pipeline on a hosted agent that calls the Node SDK a few hundred times I get the timeout issue. You can see the failing test run [here](https://dev.azure.com/richardfennell/GitHub/_releaseProgress?_a=release-environment-logs&releaseId=1879&environmentId=5709)
- If I run exactly the same pipeline on a private agent (on my development PC) I do not, it works fine.

So, I have built a test harness to try to force a timeout locally. This test harness run the same basic logic my task, the one that is timing out. However, not matter how fast/repeatedly I call the API from my development PC I cannot force a timeout. The basic test harness is

```
async function run (): Promise<string> {
    var promise = new Promise<string>(async (resolve, reject) => {

        let token: string = "<A PAT>";
        var teamProject = "GitHub"
        let authHandler = webApi.getPersonalAccessTokenHandler(token); 
        let vsts = new webApi.WebApi("https://dev.azure.com/richardfennell", authHandler);
        var buildApi: IBuildApi = await vsts.getBuildApi();

        let builds = await buildApi.getBuilds( teamProject , [53]);
        console.log(`Found ${builds.length} builds`);
        for (var build of builds) {
            console.log(`Getting the details of ${build.id}`);
            var buildCommits = await buildApi.getBuildChanges(teamProject, build.id);
            var buildWorkitems = await buildApi.getBuildWorkItemsRefs(teamProject, build.id);
        }

        resolve (`Called API {1+(2*builds.length)} times`);
   });
   return promise;
}
```

I guess the question is what difference between a private agent and a hosted one that could cause this issue. It is not as if the hosted agents are that fast, but they do have very hast connection to the internet

**Comment by rfennell** [comment]
I have now also run my test harness node app in an Azure hosted VM - this did not work show the error, so it seems specific to the hosted build agent

**Comment by rfennell** [comment]
I am still seeing this issue

**Comment by pchaploutskii** [comment]
Echoing @rfennell
Hey @stephenmichaelf any updates on this issue?

**Comment by johnnyreilly** [comment]
We've been experiencing increased flakiness from the Azure DevOps APIs lately, with the PR related endpoints being particularly problematic. We've reported this repeatedly to Microsoft / Azure but have received no meaningful support unfortunately. Our approach now is to implement an exponential back off when calling the APIs - essentially working around the degraded reliability. I'd recommend doing the same as Azure DevOps is not receiving the attention it merits at present. It brings me no pleasure to write this.

**Comment by mmrazik** [comment]
This issue is marked as an question and is discussing multiple things. I don't even know how to answer "any updates on this issue". Is the ask for update about better/built-in retry support in the azure-devops-node-api?

What I can tell from rfennell's comment he is rather trying to get to the bottom of what is wrong/different with the MS hosted agents and why are those running into timeouts. For that this is not quite the right repo. The MS hosted agents are shared between GH actions and ADO pipelines so "ADO not receiving the attention it merits" is not the issue here. There are also many important details which might not be good to discuss on a public issue -- e.g. what is the ADO organization name and in which geo it is. It also would be good to isolate the issue further and try to strip down unnecessary parts (like using azure-devops-node-api and rather calling the REST APIs directly; trying the same with GH actions as that is using different agent/runner implementation, etc).

If you see increased reliability problems on ADO APIs and can back it up by data I certainly recommend reaching out to Microsoft Support.

**Comment by johnnyreilly** [comment]
> If you see increased reliability problems on ADO APIs and can back it up by data I certainly recommend reaching out to Microsoft Support.

I have done this repeatedly and provided evidence detailing exactly when we have experienced the issue. We raised our issue with Microsoft Support in early December and still have yet to get any meaningful support provided. 

I can't speak to the initial posters issue, I mentioned on this chat because this is how our problems with the Azure DevOps APIs presented, and I wanted others who might be experiencing that issue to have the information that I have. 

With great regret, it seems that Azure DevOps is not getting the level of attention that perhaps it merits. And the support to paying customers is not adequate at present.

I'll try and share some specific details on this thread when I get to my work computer.

**Comment by johnnyreilly** [comment]
I thought I'd share our Azure support ticket and some of the details if there's anyone on the MS side that might see this and be able to help.  The below was reported on December 6th 2024 and remains open.

## Azure DevOps API unreliability - Support ID: 2412050050004373

We have an Azure DevOps custom task extension that uses the Azure DevOps API to query work items / pull requests / git commits etc. We recently noticed that the task was regularly failing and determined this was due to the Azure DevOps API behaving unreliably.

This impacted the ability of Investec to deliver software to production environments as Investec depends upon Stamp, and consequently Azure DevOps, to automate our release pipelines.

We use the Azure DevOps API through the medium of the Microsoft Node API library: https://github.com/microsoft/azure-devops-node-api. We observed failures when calling [`gitApi.getPullRequestWorkItemRefs`](https://github.com/microsoft/azure-devops-node-api/blob/d5bd85cd2e44f8ad89f7257a6a9947f5e91c578a/api/GitApi.ts#L6163). Digging into the codebase of the Microsoft Node API library, we understand that the following endpoint was being called and so appears to be the only one having issues: [Pull Request Work Items - List](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-work-items/list?view=azure-devops-rest-7.2)

We [reported the issue to Microsoft 6th December 2024](https://portal.azure.com/#view/Microsoft_Azure_Support/SupportRequestDetails.ReactView/id/%2Fsubscriptions%2F5b380244-4d89-4218-a9ad-e6295602f103%2Fproviders%2FMicrosoft.Support%2FsupportTickets%2Fcd9d74ec-9d1b4757-514c45c3-74fe-4b50-bfb9-846567fbb07a) through the Azure Portal. We understand from our engineering community that these issues have been present for up to a month - though we do not have a firm start date.

---

If others have details they can share I'd encourage them to.

**Comment by johnnyreilly** [comment]
I thought I'd share our Azure support ticket and some of the details if there's anyone on the MS side that might see this and be able to help.  The below was reported on December 6th 2024 and remains open.

## Azure DevOps API unreliability - Support ID: 2412050050004373

We have an Azure DevOps custom task extension that uses the Azure DevOps API to query work items / pull requests / git commits etc. We recently noticed that the task was regularly failing and determined this was due to the Azure DevOps API behaving unreliably.

This impacted the ability of our company to deliver software to production environments as we depend upon this extension, and consequently Azure DevOps, to automate our release pipelines.

We use the Azure DevOps API through the medium of the Microsoft Node API library: https://github.com/microsoft/azure-devops-node-api. We observed failures when calling [`gitApi.getPullRequestWorkItemRefs`](https://github.com/microsoft/azure-devops-node-api/blob/d5bd85cd2e44f8ad89f7257a6a9947f5e91c578a/api/GitApi.ts#L6163). Digging into the codebase of the Microsoft Node API library, we understand that the following endpoint was being called and so appears to be the only one having issues: [Pull Request Work Items - List](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-work-items/list?view=azure-devops-rest-7.2)

We [reported the issue to Microsoft 6th December 2024](https://portal.azure.com/#view/Microsoft_Azure_Support/SupportRequestDetails.ReactView/id/%2Fsubscriptions%2F5b380244-4d89-4218-a9ad-e6295602f103%2Fproviders%2FMicrosoft.Support%2FsupportTickets%2Fcd9d74ec-9d1b4757-514c45c3-74fe-4b50-bfb9-846567fbb07a) through the Azure Portal. We understand from our engineering community that these issues have been present for up to a month - though we do not have a firm start date.

---

If others have details they can share I'd encourage them to.
