### ISSUE TITLE
Can't get suites for a plan

### ISSUE THREAD

**Issue by bkapellusch** [microsoft/azure-devops-node-api#412]
I can get plans from the work API, and if I have a suiteId, I can get test cases from the test API. But I can't seem to find a node API call that matches this REST call:

https://docs.microsoft.com/en-us/rest/api/azure/devops/test/test%20%20suites/get%20test%20suites%20for%20plan?view=azure-devops-rest-5.0

Is it just not implemented? Or am I looking in the wrong spot?

**Comment by midmarch** [comment]
I am not sure how we can contribute to the project as the API is generated from a source which seems to not documented as part of this project.

I believe the issue is that essentially the [**Test Plans** API of the Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/testplan/test-plans) is not generated.

As a dirty workaround, to retrieve test suites a test planned composed of, one case use this function: 
```js
/**
 * Get all test suites in a plan
 *
 * @param {ClientApiBase} - Test API
 * @param {string} adoProject - Project ID or project name
 * @param {number} planId - ID of the test plan that contains the suites.
 */
async function getTestSuits(clientApi, adoProjectname, planId) {

  const url = `${clientApi.vsoClient.baseUrl}/${adoProjectname}/_apis/testplan/Plans/${planId}/Suites/`;
  const res = await clientApi.rest.get(url);
  return clientApi.formatResponse(res.result, null, true);
}
```
