### ISSUE TITLE
WikiApi appears to be missing "Pages - Create Or Update" parts of API 

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-devops-node-api#431]
Opening this as the bot closed #416 despite appeals

Hello again!

I've been working on writing a tool that writes to our Wiki.   However it looks like the ["Pages - Create Or Update"](https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create%20or%20update?view=azure-devops-rest-6.0) portion of the API hasn't been implemented.

If you take a look at `WikiApi` you'll see the following `page` operations implemented:

https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/WikiApi.ts#L33-L38

However, we're missing a `createOrUpdatePage` method.  [According to the REST API docs here](https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create%20or%20update?view=azure-devops-rest-6.0) this endpoint exists.  Is there any chance that it could added please?  As is, it does not appear to be possible to add new pages using the client.

**Comment by max-zaytsev** [comment]
Hi @johnnyreilly, most of the code here is auto-generated from API definitions, and apparently, some methods cannot be generated for nodejs due to the limitations of the generation tool.
In this case, we advise customers to hit the endpoint directly through an http call (or using the [typed-rest-client](https://github.com/microsoft/typed-rest-client))

**Comment by oliverpechey** [comment]
Just commenting to say this would have been nice. I find it odd that this tool is missing API routes.

Thanks for the workaround guide in #416 Johnny!
