### ISSUE TITLE
`isBrowser` check erroneously passes for `electron-link` bundled `node` applications

### ISSUE THREAD

**Issue by themadtitanmathos** [microsoft/azure-devops-node-api#436]
azure-devops-node-api version: 10.2.1

### Issue Description
`global.window` gets set in `electron-link` bundled applications, but `global.window.navigator` won't exist because it isn't a browser app, it's a node app. This means the current `isBrowser` check isn't quite enough, and the `WebApi` constructor will fail while trying to set the `userAgent` by accessing an undefined `window.navigator.userAgent`. I think a simple fix would be to also check `window.navigator` exists when calculating `isBrowser`.

### Expected behaviour
`isBrowser` should not be `true` for `electron-link` (or any `electron` bundled) node apps.

### Actual behaviour
`isBrowser` is true for `electron-link` (or possibly other `electron` bundled) node apps.

**Comment by Dobby007** [comment]
The issue is still relevant. There is a discussion that is relevant to this: https://github.com/electron/electron/issues/2288

[The latest recommendation](https://github.com/electron/electron/issues/2288#issuecomment-611231970) up there is to use `process.versions.hasOwnProperty('electron')` in the main process. That's probably what should be done because `navigator.userAgent` is defined in the renderer so there will be no issues with it (although nobody should invoke API in the renderer).

CC @anatolybolshakov
