### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-node-api#543]
How so that I can't find any release notes given the new major version has been released? There are breaking changes and no word about them.
Could you at least tag the repo before publishing a new version so that we can go through changes with ease on our own?

**Comment by DmitriiBobreshev** [comment]
Hi @mmajcica, we're so sorry about that, [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api/issues/543) is mostly autogenerated repository based on ADO, we had an [update recently](https://github.com/microsoft/azure-devops-node-api/pull/539) based on new ADO release M216 sprint with API changes, we'll try to implement changelog generation/release note on this to prevent a situation like this. For now unfortunately it's not possible, so you could pay extra attention when updating major versions. 
As a temporary solution, because this repo is based on ADO API, you can track [ADO release notes](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-215-update#azure-pipelines-1).
Sorry again and thank you for the feedback!

**Comment by mmajcica** [comment]
Thanks, @DmitriiBobreshev 

For others facing the same question;
From what I can see, the only breaking change is located in TaskAgentApi where the interface has been changed by removing the acquireAccessToken method.

**Comment by mmajcica** [comment]
Non breaking changes worth mentioning;

GitApi method getItems got another parameter called zipForUnix
